### ISSUE TITLE
Finalize palette for MACILE

### ISSUE THREAD

**Issue by misscs** [cosola-salvia/macile-newsletter#98]
We want to create the color palette for MACILE. The idea is to have a set of colors that we can use to design pages/sections of the macile.org site, this includes the newsletter and bulletin.

Use https://color.adobe.com/create/color-wheel to develop varios color palettes.

- [x] Generate some color palettes based on MACILE.org colors
- [x] Present color options to @misscs @cosola

**Comment by lehysen** [comment]
(
![image](https://user-images.githubusercontent.com/29067344/80971731-2d982c80-8deb-11ea-972a-d895cd15ecc5.png)
)
(
![image](https://user-images.githubusercontent.com/29067344/80971871-5f10f800-8deb-11ea-8fef-e793582afddd.png)
)
(
![image](https://user-images.githubusercontent.com/29067344/80972059-a303fd00-8deb-11ea-9693-e96b73ab2f5d.png)
)
(
![image](https://user-images.githubusercontent.com/29067344/80972126-b9aa5400-8deb-11ea-8be2-eab1efaf80af.png)
)

**Comment by lehysen** [comment]
(
![image](https://user-images.githubusercontent.com/29067344/80972445-1d348180-8dec-11ea-8027-cdce04c2b80e.png)
)
(
![image](https://user-images.githubusercontent.com/29067344/80972663-61c01d00-8dec-11ea-8b07-1359452ed14b.png)
)
(
![image](https://user-images.githubusercontent.com/29067344/80973999-21619e80-8dee-11ea-8240-c7991f7cda5a.png)
)
(
![image](https://user-images.githubusercontent.com/29067344/80972862-9f24aa80-8dec-11ea-8e2e-a0a7c3c96cde.png)
)

**Comment by misscs** [comment]
#### standup 06-05-2020

- Completed another round of color palettes, will share after standup for team review.

**Comment by lehysen** [comment]
(
![image](https://user-images.githubusercontent.com/29067344/81222259-ff187e00-8fb1-11ea-8d51-1a1e3b81873c.png)
)
(
![image](https://user-images.githubusercontent.com/29067344/81222288-0e97c700-8fb2-11ea-986d-d80ad1889303.png)
)
(
![image](https://user-images.githubusercontent.com/29067344/81222324-19525c00-8fb2-11ea-8639-2a2ee61fcfbf.png)
)
(
![image](https://user-images.githubusercontent.com/29067344/81222357-2bcc9580-8fb2-11ea-90a1-a42cf0c82715.png)
)

**Comment by misscs** [comment]
@MariaGuillen @Morban15 What do you think? What suggestions do you have? Feel free to play around with the color wheel using the link above.

**Comment by Morban15** [comment]
De las opciones de @lehysen me gusta la última. Aquí tengo otras opciones.

![palette-color-1](https://user-images.githubusercontent.com/29107510/81397452-5bd08180-90f5-11ea-858a-df399718375f.png)

![palette-color-2](https://user-images.githubusercontent.com/29107510/81397460-60953580-90f5-11ea-95a3-1d0a12bc207c.png)

![palette-color-3](https://user-images.githubusercontent.com/29107510/81397472-6559e980-90f5-11ea-937b-13181864439f.png)

![palette-color-4](https://user-images.githubusercontent.com/29107510/81397481-6ab73400-90f5-11ea-83ee-2ead5b0a460c.png)

![palette-color-5](https://user-images.githubusercontent.com/29107510/81397487-6ee35180-90f5-11ea-81c1-8d7d00d61e1f.png)

**Comment by MariaGuillen** [comment]
Estas paletas me gustan como opción para títulos y subtítulos 
 ![image](https://user-images.githubusercontent.com/29066354/81420753-6c492200-911e-11ea-841c-7555e1e94727.jpeg)

![image](https://user-images.githubusercontent.com/29066354/81420767-71a66c80-911e-11ea-8955-6cea071e778e.jpeg)

Estas como opciones para background

![image](https://user-images.githubusercontent.com/29066354/81420840-8c78e100-911e-11ea-880c-18f420ff0bc7.jpeg)

![image](https://user-images.githubusercontent.com/29066354/81420857-91d62b80-911e-11ea-93cf-9253d95ad029.jpeg)

![image](https://user-images.githubusercontent.com/29066354/81420873-97337600-911e-11ea-9d93-c03e620e2ee3.jpeg)

**Comment by cosola** [comment]
FYI: @lehysen  @MariaGuillen  @Morban15 @misscs 

You have done a great job constructing color pallets.  We can make good use of some of them; however, the following guidelines must be observed. 

### These are the branding colors of MACILE
* Gray  RGB(167, 169, 172)
* Yellow RGB(253, 253, 86)
* Gold RGB(181, 135, 45)
* Blue RGB(21, 21, 78)
* White RGB (255, 255, 255)

### Guidelines for color selection

* We will observe the brand colors in ALL MACILE pages. But complementary and contrast colors can be included or used instead of or in addition to a color.

* The Blue color should ALWAYS be included and it should be present in the top nav.

* Remember to follow Mrs. Showalter's suggestion.

* The color selected for the footer should be the same throughout all pages. However, in some pages the footer may have 2 or more levels, like when it is also used as a nav. In this case, a second color or two variations of the same color can be selected.

* I suggest to avoid excessive use of dark colors

### Guidelines for logo and slogan

 * The MACILE logo is a combination of the word MACILE and the crest.  Both should appear in all pages. But they don't have to be one next to the other in all pages.

* The words: mathematics, science, engineering, and language are part of the brand. They are important because some people do not know what MACILE stands for.

* "Advancing Engineering and Technology Education" is the slogan, which indicates the focus of our education the program. This is often extended to include the phrase "in less-advantaged communities," which indicates the population we serve.

* "Seek Learning And Understanding" is the brand. It indicates that we believe you can learn anything you want to learn, if you are determined to and willing to persevere. 

Hope I have clarified any confusion. 

Thanks for the wonderful job.

**Comment by misscs** [comment]
We have a brand guidelines document in Guías. That is where the color selection is coming from. The RGB values are being used, just converted to HEX. 

Can you add your recommendations and guidelines to that document? We don’t want to love them. Thanks!

Also, do you have any suggestions or direct feedback on the colors so we can move this issue forward?

**Comment by misscs** [comment]
#### standup 11 may

- Dr. Vargas will add her color selection
- Final choice is up to the students to pick the colors they would like to use
- @Morban15 needs to add the color values for her palettes. Try finding a color picker or ask a teammate to help you out if you're having issues with the internet

As we discussed, we may just end up finalizing the list later, but we can move forward experimenting with these colors.

**Comment by Morban15** [comment]
![palette-color-mod-3](https://user-images.githubusercontent.com/29107510/81612408-c65e1780-93aa-11ea-82f3-dacadf79cfa8.png)

![palette-color-mod-4](https://user-images.githubusercontent.com/29107510/81612416-c78f4480-93aa-11ea-9f7c-b22d37b2a266.png)

![palette-color-mod-5](https://user-images.githubusercontent.com/29107510/81612419-c827db00-93aa-11ea-8582-4ace47ecf911.png)

![palette-color-mod-1](https://user-images.githubusercontent.com/29107510/81612421-c8c07180-93aa-11ea-84d5-da38363d7dcc.png)

![palette-color-mod-2](https://user-images.githubusercontent.com/29107510/81612424-c8c07180-93aa-11ea-8a7c-3b84d3caae08.png)

**Comment by misscs** [comment]
Gracias @Morban15. Great. 

I'm making a Figma file with the colors to easily reference them in designs.

**Comment by misscs** [comment]
@MariaGuillen @lehysen @cosola @Morban15 Bonus, the figma file makes it easy to get the HSL values. No need to convert them. I will send out invites tonight and tomorrow during standup we can take a look at it. I hope it works with slower connections.

**Comment by misscs** [comment]
@lehysen What is the hex code for the last purple swatch?

![image](https://user-images.githubusercontent.com/51812/81617032-a3376600-93b2-11ea-93ae-89094b74756e.png)

**Comment by lehysen** [comment]
#A856FC

**Comment by misscs** [comment]
#### standup 12-05-2020

- Dr. Vargas did not add her comments. Due to time, we're going to move ahead with selection by the students
- @misscs moved colors into Figma
